# Generated by Django 6.0.2 on 2026-02-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEJAL2005app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
